import React, {useCallback, useEffect, useState} from 'react';
import {View, StyleSheet} from 'react-native';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  searchTxtInput: {
    borderRadius: 7,
    paddingHorizontal: 45,
    borderWidth:1,
    backgroundColor: '#e6ecf5',
  },
  ourMenu: {
    color: '#000518',
    fontWeight: '800',
    fontSize: 16,
  },
  viewAll: {
    fontWeight: '800',
    color: '#ff146c',
    fontSize: 10,
  },
  categoryText: {
    fontSize: 10,
    color: '#000518',
    fontWeight: '600',
    textAlign: 'center',
  },
  featuredContainer: {
    backgroundColor: 'white',
    // flex: 0.5,
    width: '100%',
    height: 220,
    borderRadius: 10,
    // marginRight: 5,
    elevation: 0.5,
    shadowColor:"blue",
    // borderWidth: 0.5,
    borderColor: '#e6ecf5',
  },
  featuredImag: {
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  imgSub: {
    flexDirection: 'row',
    marginHorizontal: 2,
    marginTop: 8,
  },
  text: {
    fontSize: 13,
    fontWeight: '800',
    color: '#000518',
  },
  info: {
    flex: 0.1,
    backgroundColor: 'white',
    justifyContent: 'flex-end',
    paddingLeft:3
  },
  price: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
    marginTop:20,
    backgroundColor: 'white',
  },
  add: {
    justifyContent: 'center',
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    elevation: 3,
  },
  addText: {
    fontSize: 10,
    color: '#ff146c',
    fontWeight: 'bold',
  },
  title: {
    color: '#000518',
    fontWeight: '800',
    fontSize: 16,
    marginHorizontal: 20,
    marginTop: 10,
  },
  top: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 10,
  },
  Search: {backgroundColor: 'white', marginHorizontal: 20, marginVertical: 15},
  our: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 15,
  },
  View: {
    backgroundColor: '#FFD9E7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  category: {
    backgroundColor: 'white',
    borderRadius: 8,
    // justifyContent: 'center',
    // alignItems: 'center',
    // width: 100,
    // padding: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    // elevation: 5,
    shadowOpacity: 1,
    shadowColor: '#b0c4de',
    marginTop: 10,
    marginBottom: 5,
  },
  categoryContainer: {
    backgroundColor: 'white',
    paddingVertical:10
  },
  noData: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  cat: {
    backgroundColor: 'white',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
    width: 90,
    // padding: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginHorizontal: 5,
    elevation: 10,
    shadowOpacity: 1,
    shadowColor: '#b0c4de',
    marginVertical: 10,
  },
});
export default style;
